//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBAutoDispatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHBoydUpload
    {
        public int AssetID { get; set; }
        public int EventID { get; set; }
        public int ScheduleID { get; set; }
        public Nullable<double> CONTACTID { get; set; }
        public string FULFILLMENTSTATUS { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public string MAXOFSTARTDATETIME { get; set; }
        public string MAXOFARRIVALDATETIME { get; set; }
        public Nullable<System.DateTime> MAXOFCOMPLETIONDATETIME { get; set; }
        public Nullable<double> NOSERVICE { get; set; }
        public Nullable<double> EVENTCALLTYPEID { get; set; }
        public string CALLTYPEDESC { get; set; }
        public string COMPANYNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTALCODE { get; set; }
        public string FIELDSERVICEMANAGER { get; set; }
        public Nullable<double> FSMJDE { get; set; }
        public string PRICINGPARENTNAME { get; set; }
        public string DELIVERYDESC { get; set; }
        public string ERFNO { get; set; }
        public string TECHID { get; set; }
        public string RECALLEVENT { get; set; }
        public string EQUIPCOUNT { get; set; }
        public string DEALERCOMPANY { get; set; }
        public string DEALERCITY { get; set; }
        public string DEALERSTATE { get; set; }
        public Nullable<double> CALLTYPEID { get; set; }
        public string SYMPTOMID { get; set; }
        public Nullable<double> SOLUTIONID { get; set; }
        public string SYSTEMID { get; set; }
        public string SERIALNO { get; set; }
        public string PRODUCTNO { get; set; }
        public string MANUFACTURER { get; set; }
        public string MANUFACTURERDESC { get; set; }
        public string APPOINTMENTDATE { get; set; }
        public string CATEGORYDESC { get; set; }
        public string INVOICENO { get; set; }
        public string FAMILYAFF { get; set; }
        public string ADT { get; set; }
        public string ONSITE { get; set; }
        public string CUSTOMERREGION { get; set; }
        public string BRANCH { get; set; }
        public Nullable<double> REGIONNUMBER { get; set; }
        public string CUSTOMERBRANCH { get; set; }
        public Nullable<double> BRANCH_1 { get; set; }
        public string CONTACTSEARCHTYPE { get; set; }
        public string CONTACTSEARCHDESC { get; set; }
        public string ROUTENUMBER { get; set; }
        public string PPID { get; set; }
        public string PPIDDESC { get; set; }
        public string PRICINGPARENTID { get; set; }
        public Nullable<short> RecExists { get; set; }
        public Nullable<short> ContactExists { get; set; }
        public string CustPhone { get; set; }
        public Nullable<int> WorkorderTimeZone { get; set; }
        public string WorkorderDaylightSaving { get; set; }
    }
}
