//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBAutoDispatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHUpdTechName
    {
        public Nullable<int> EventID { get; set; }
        public int DealerId { get; set; }
        public string CompanyName { get; set; }
        public string ResponsibleTechName { get; set; }
    }
}
