//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERFUploadDataDec272024
    {
        public Nullable<double> Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> LadinCost { get; set; }
        public Nullable<decimal> CashSale { get; set; }
        public Nullable<decimal> Rental { get; set; }
        public bool IsActive { get; set; }
        public string ContingentName { get; set; }
    }
}
