//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBWindowsServiceAsConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBReport1
    {
        public int WorkorderID { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string WorkorderCallstatus { get; set; }
        public string PurchaseOrder { get; set; }
        public string BillingID { get; set; }
        public string WorkorderErfid { get; set; }
        public Nullable<System.DateTime> WorkorderCloseDate { get; set; }
        public Nullable<short> WorkorderEquipCount { get; set; }
        public string State { get; set; }
        public string ThirdPartyPO { get; set; }
        public Nullable<decimal> Estimate { get; set; }
        public Nullable<decimal> FinalEstimate { get; set; }
        public string JREvents { get; set; }
        public Nullable<int> OriginalWorkorderid { get; set; }
        public Nullable<int> WorkorderCalltypeid { get; set; }
        public string TechCalled { get; set; }
        public string DESCF { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> OriginalRequestedDate { get; set; }
        public Nullable<System.DateTime> DateERFReceived { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> OrgCustReqDate { get; set; }
        public Nullable<System.DateTime> EquipETADate { get; set; }
        public string ERFComplete { get; set; }
        public Nullable<bool> NoServiceRequired { get; set; }
        public string NoServiceReason { get; set; }
        public string DELTA { get; set; }
    }
}
