//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBPowerReport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FBEntities : DbContext
    {
        public FBEntities()
            : base("name=FBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllFBStatu> AllFBStatus { get; set; }
        public virtual DbSet<BranchESM> BranchESMs { get; set; }
        public virtual DbSet<BrandName> BrandNames { get; set; }
        public virtual DbSet<CallTypeSymptomSolutionMaster> CallTypeSymptomSolutionMasters { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contingent> Contingents { get; set; }
        public virtual DbSet<ContingentDetail> ContingentDetails { get; set; }
        public virtual DbSet<EquipType> EquipTypes { get; set; }
        public virtual DbSet<Erf> Erfs { get; set; }
        public virtual DbSet<ERFBranchDetail> ERFBranchDetails { get; set; }
        public virtual DbSet<ERFOrderType> ERFOrderTypes { get; set; }
        public virtual DbSet<ESMCCMRSMEscalation> ESMCCMRSMEscalations { get; set; }
        public virtual DbSet<ESMDSMRSM> ESMDSMRSMs { get; set; }
        public virtual DbSet<EstimateEscalation> EstimateEscalations { get; set; }
        public virtual DbSet<FBActivityLog> FBActivityLogs { get; set; }
        public virtual DbSet<FBBillableFeed> FBBillableFeeds { get; set; }
        public virtual DbSet<FbBillableSKU> FbBillableSKUs { get; set; }
        public virtual DbSet<FBCallReason> FBCallReasons { get; set; }
        public virtual DbSet<FBCBE> FBCBEs { get; set; }
        public virtual DbSet<FBClosurePart> FBClosureParts { get; set; }
        public virtual DbSet<FBCustomerNote> FBCustomerNotes { get; set; }
        public virtual DbSet<FBCustomerServiceDistribution> FBCustomerServiceDistributions { get; set; }
        public virtual DbSet<FBEquipment> FBEquipments { get; set; }
        public virtual DbSet<FBERFEquipment> FBERFEquipments { get; set; }
        public virtual DbSet<FBERFExpendable> FBERFExpendables { get; set; }
        public virtual DbSet<FBERFTransactionType> FBERFTransactionTypes { get; set; }
        public virtual DbSet<FBExpendable> FBExpendables { get; set; }
        public virtual DbSet<FBFunctionality> FBFunctionalities { get; set; }
        public virtual DbSet<FbPrimaryTechnician> FbPrimaryTechnicians { get; set; }
        public virtual DbSet<FBReport> FBReports { get; set; }
        public virtual DbSet<FBRoleFunction> FBRoleFunctions { get; set; }
        public virtual DbSet<FbRole> FbRoles { get; set; }
        public virtual DbSet<FBSKU> FBSKUs { get; set; }
        public virtual DbSet<FbUserMaster> FbUserMasters { get; set; }
        public virtual DbSet<FBUserReport> FBUserReports { get; set; }
        public virtual DbSet<FbWorkOrderSKU> FbWorkOrderSKUs { get; set; }
        public virtual DbSet<IndexCounter> IndexCounters { get; set; }
        public virtual DbSet<NonFBCustomer> NonFBCustomers { get; set; }
        public virtual DbSet<NonSerialized> NonSerializeds { get; set; }
        public virtual DbSet<NonServiceworkorder> NonServiceworkorders { get; set; }
        public virtual DbSet<NotesHistory> NotesHistories { get; set; }
        public virtual DbSet<OnCallGroup> OnCallGroups { get; set; }
        public virtual DbSet<PhoneSolveLog> PhoneSolveLogs { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<RemovalSurvey> RemovalSurveys { get; set; }
        public virtual DbSet<Sku> Skus { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<SystemInfo> SystemInfoes { get; set; }
        public virtual DbSet<TECH_HIERARCHY> TECH_HIERARCHY { get; set; }
        public virtual DbSet<TechOnCall> TechOnCalls { get; set; }
        public virtual DbSet<TechSchedule> TechSchedules { get; set; }
        public virtual DbSet<ThirdpartyConMaintenanceZonerate> ThirdpartyConMaintenanceZonerates { get; set; }
        public virtual DbSet<ThirdPartyContractMaintenance> ThirdPartyContractMaintenances { get; set; }
        public virtual DbSet<TMP_BlackBerry_NSR> TMP_BlackBerry_NSR { get; set; }
        public virtual DbSet<TMP_BlackBerry_SCFAssetInfo> TMP_BlackBerry_SCFAssetInfo { get; set; }
        public virtual DbSet<TMP_BlackBerry_SCFPartsInfo> TMP_BlackBerry_SCFPartsInfo { get; set; }
        public virtual DbSet<UserApplication> UserApplications { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkOrderBrand> WorkOrderBrands { get; set; }
        public virtual DbSet<WorkorderDetail> WorkorderDetails { get; set; }
        public virtual DbSet<WorkorderEquipment> WorkorderEquipments { get; set; }
        public virtual DbSet<WorkorderEquipmentRequested> WorkorderEquipmentRequesteds { get; set; }
        public virtual DbSet<WorkorderImage> WorkorderImages { get; set; }
        public virtual DbSet<WorkorderInstallationSurvey> WorkorderInstallationSurveys { get; set; }
        public virtual DbSet<WorkorderNonAudit> WorkorderNonAudits { get; set; }
        public virtual DbSet<WorkorderPart> WorkorderParts { get; set; }
        public virtual DbSet<WorkorderReasonlog> WorkorderReasonlogs { get; set; }
        public virtual DbSet<WorkorderSavedSearch> WorkorderSavedSearches { get; set; }
        public virtual DbSet<WorkorderSchedule> WorkorderSchedules { get; set; }
        public virtual DbSet<WorkorderType> WorkorderTypes { get; set; }
        public virtual DbSet<ZonePriority> ZonePriorities { get; set; }
        public virtual DbSet<FBReport1> FBReports1 { get; set; }
        public virtual DbSet<PMUploads_All> PMUploads_All { get; set; }
        public virtual DbSet<TMP_BlackBerry_SCFInvoiceInfo> TMP_BlackBerry_SCFInvoiceInfo { get; set; }
        public virtual DbSet<Tmp_PMUploads> Tmp_PMUploads { get; set; }
        public virtual DbSet<TMP_SerialNOReport> TMP_SerialNOReport { get; set; }
        public virtual DbSet<Zip> Zips { get; set; }
        public virtual DbSet<ZoneZip> ZoneZips { get; set; }
    }
}
