//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBPowerReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_PMUploads
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string ReoccurringDuration { get; set; }
        public string IntervalType { get; set; }
        public Nullable<System.DateTime> EventID { get; set; }
        public Nullable<double> CustomerJDE { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<double> TechID { get; set; }
        public string TechName { get; set; }
        public string EquipCallType { get; set; }
        public string NOTES { get; set; }
        public Nullable<double> ProjectNumber { get; set; }
        public string EventContact { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string Zip { get; set; }
        public string DaylightSaving { get; set; }
    }
}
